language: elixir
elixir: 1.7
otp_release: 21.2
services:
  - docker
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-client
env:
  global:
    - MYSQL_SOCKET_DIR=/var/run/mysqld
    - MYSQL_UNIX_PORT=/var/run/mysqld/mysqld.sock
  matrix:
    - DB=mysql:8.0
    - DB=mysql:5.7 FORCE_TLS11=true
    - DB=mariadb:10.4
matrix:
  include:
    - elixir: 1.4
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 19.3
    - script:
        - mix compile --warnings-as-errors
        - mix format --check-formatted
script:
  - ./ci.sh
